BASE_PROBABILITIES = {'S': 0.05, 'A': 0.15, 'B': 0.35, 'C': 0.45}
S_HARD_PITY = 25
S_SOFT_PITY_START = 20
S_SOFT_PITY_CAP = 0.15
S_SLOPE = (S_SOFT_PITY_CAP - BASE_PROBABILITIES['S']) / (S_HARD_PITY - 1 - S_SOFT_PITY_START - 1)
S_INTERCEPT = S_SOFT_PITY_CAP - (S_SLOPE * S_HARD_PITY - 1)
A_HARD_PITY = 8
A_SOFT_PITY_START = 5
A_SOFT_PITY_CAP = 0.30
A_SLOPE = (A_SOFT_PITY_CAP - BASE_PROBABILITIES['A']) / (A_HARD_PITY - 1 - A_SOFT_PITY_START - 1)
A_INTERCEPT = A_SOFT_PITY_CAP - (A_SLOPE * A_HARD_PITY - 1)



